/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRouteImport } from './routes/api'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as RunsRouteRouteImport } from './routes/runs/route'
import { Route as StartRouteImport } from './routes/start'
import { Route as WorkflowsRouteRouteImport } from './routes/workflows/route'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as RunsIdRouteImport } from './routes/runs/$id'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as WorkflowsNameRouteImport } from './routes/workflows/$name'
import { Route as ApiRunsIndexRouteImport } from './routes/api/runs/index'
import { Route as ApiRunsIdIndexRouteImport } from './routes/api/runs/$id/index'
import { Route as ApiRunsIdApprovalsApprovalIdRouteImport } from './routes/api/runs/$id/approvals/$approvalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRouteRoute = RunsRouteRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRouteRoute = WorkflowsRouteRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiRoute,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ApiRoute,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunsRouteRoute,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RunsRouteRoute,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkflowsRouteRoute,
} as any)
const WorkflowsNameRoute = WorkflowsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => WorkflowsRouteRoute,
} as any)
const ApiRunsIndexRoute = ApiRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => ApiRoute,
} as any)
const ApiRunsIdIndexRoute = ApiRunsIdIndexRouteImport.update({
  id: '/runs/$id/',
  path: '/runs/$id/',
  getParentRoute: () => ApiRoute,
} as any)
const ApiRunsIdApprovalsApprovalIdRoute =
  ApiRunsIdApprovalsApprovalIdRouteImport.update({
    id: '/runs/$id/approvals/$approvalId',
    path: '/runs/$id/approvals/$approvalId',
    getParentRoute: () => ApiRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/runs': typeof RunsRouteRouteWithChildren
  '/workflows': typeof WorkflowsRouteRouteWithChildren
  '/api': typeof ApiRouteWithChildren
  '/inbox': typeof InboxRoute
  '/start': typeof StartRoute
  '/api/$': typeof ApiSplatRoute
  '/api/config': typeof ApiConfigRoute
  '/runs/$id': typeof RunsIdRoute
  '/workflows/$name': typeof WorkflowsNameRoute
  '/runs/': typeof RunsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/api/runs/': typeof ApiRunsIndexRoute
  '/api/runs/$id/': typeof ApiRunsIdIndexRoute
  '/api/runs/$id/approvals/$approvalId': typeof ApiRunsIdApprovalsApprovalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/inbox': typeof InboxRoute
  '/start': typeof StartRoute
  '/api/$': typeof ApiSplatRoute
  '/api/config': typeof ApiConfigRoute
  '/runs/$id': typeof RunsIdRoute
  '/workflows/$name': typeof WorkflowsNameRoute
  '/runs': typeof RunsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/api/runs': typeof ApiRunsIndexRoute
  '/api/runs/$id': typeof ApiRunsIdIndexRoute
  '/api/runs/$id/approvals/$approvalId': typeof ApiRunsIdApprovalsApprovalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/runs': typeof RunsRouteRouteWithChildren
  '/workflows': typeof WorkflowsRouteRouteWithChildren
  '/api': typeof ApiRouteWithChildren
  '/inbox': typeof InboxRoute
  '/start': typeof StartRoute
  '/api/$': typeof ApiSplatRoute
  '/api/config': typeof ApiConfigRoute
  '/runs/$id': typeof RunsIdRoute
  '/workflows/$name': typeof WorkflowsNameRoute
  '/runs/': typeof RunsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/api/runs/': typeof ApiRunsIndexRoute
  '/api/runs/$id/': typeof ApiRunsIdIndexRoute
  '/api/runs/$id/approvals/$approvalId': typeof ApiRunsIdApprovalsApprovalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/runs'
    | '/workflows'
    | '/api'
    | '/inbox'
    | '/start'
    | '/api/$'
    | '/api/config'
    | '/runs/$id'
    | '/workflows/$name'
    | '/runs/'
    | '/workflows/'
    | '/api/runs/'
    | '/api/runs/$id/'
    | '/api/runs/$id/approvals/$approvalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/inbox'
    | '/start'
    | '/api/$'
    | '/api/config'
    | '/runs/$id'
    | '/workflows/$name'
    | '/runs'
    | '/workflows'
    | '/api/runs'
    | '/api/runs/$id'
    | '/api/runs/$id/approvals/$approvalId'
  id:
    | '__root__'
    | '/'
    | '/runs'
    | '/workflows'
    | '/api'
    | '/inbox'
    | '/start'
    | '/api/$'
    | '/api/config'
    | '/runs/$id'
    | '/workflows/$name'
    | '/runs/'
    | '/workflows/'
    | '/api/runs/'
    | '/api/runs/$id/'
    | '/api/runs/$id/approvals/$approvalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RunsRouteRoute: typeof RunsRouteRouteWithChildren
  WorkflowsRouteRoute: typeof WorkflowsRouteRouteWithChildren
  ApiRoute: typeof ApiRouteWithChildren
  InboxRoute: typeof InboxRoute
  StartRoute: typeof StartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/config': {
      id: '/api/config'
      path: '/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof ApiRoute
    }
    '/runs/': {
      id: '/runs/'
      path: '/'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof RunsRouteRoute
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof RunsRouteRoute
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof WorkflowsRouteRoute
    }
    '/workflows/$name': {
      id: '/workflows/$name'
      path: '/$name'
      fullPath: '/workflows/$name'
      preLoaderRoute: typeof WorkflowsNameRouteImport
      parentRoute: typeof WorkflowsRouteRoute
    }
    '/api/runs/': {
      id: '/api/runs/'
      path: '/runs'
      fullPath: '/api/runs/'
      preLoaderRoute: typeof ApiRunsIndexRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/runs/$id/': {
      id: '/api/runs/$id/'
      path: '/runs/$id'
      fullPath: '/api/runs/$id/'
      preLoaderRoute: typeof ApiRunsIdIndexRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/runs/$id/approvals/$approvalId': {
      id: '/api/runs/$id/approvals/$approvalId'
      path: '/runs/$id/approvals/$approvalId'
      fullPath: '/api/runs/$id/approvals/$approvalId'
      preLoaderRoute: typeof ApiRunsIdApprovalsApprovalIdRouteImport
      parentRoute: typeof ApiRoute
    }
  }
}

interface RunsRouteRouteChildren {
  RunsIdRoute: typeof RunsIdRoute
  RunsIndexRoute: typeof RunsIndexRoute
}

const RunsRouteRouteChildren: RunsRouteRouteChildren = {
  RunsIdRoute: RunsIdRoute,
  RunsIndexRoute: RunsIndexRoute,
}

const RunsRouteRouteWithChildren = RunsRouteRoute._addFileChildren(
  RunsRouteRouteChildren,
)

interface WorkflowsRouteRouteChildren {
  WorkflowsNameRoute: typeof WorkflowsNameRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

const WorkflowsRouteRouteChildren: WorkflowsRouteRouteChildren = {
  WorkflowsNameRoute: WorkflowsNameRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}

const WorkflowsRouteRouteWithChildren = WorkflowsRouteRoute._addFileChildren(
  WorkflowsRouteRouteChildren,
)

interface ApiRouteChildren {
  ApiSplatRoute: typeof ApiSplatRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiRunsIndexRoute: typeof ApiRunsIndexRoute
  ApiRunsIdIndexRoute: typeof ApiRunsIdIndexRoute
  ApiRunsIdApprovalsApprovalIdRoute: typeof ApiRunsIdApprovalsApprovalIdRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiSplatRoute: ApiSplatRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiRunsIndexRoute: ApiRunsIndexRoute,
  ApiRunsIdIndexRoute: ApiRunsIdIndexRoute,
  ApiRunsIdApprovalsApprovalIdRoute: ApiRunsIdApprovalsApprovalIdRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RunsRouteRoute: RunsRouteRouteWithChildren,
  WorkflowsRouteRoute: WorkflowsRouteRouteWithChildren,
  ApiRoute: ApiRouteWithChildren,
  InboxRoute: InboxRoute,
  StartRoute: StartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
