/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRouteImport } from './routes/api'
import { Route as ConnectorsRouteRouteImport } from './routes/connectors/route'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as StartRouteImport } from './routes/start'
import { Route as WorkflowsRouteRouteImport } from './routes/workflows/route'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiScenariosRouteImport } from './routes/api/scenarios'
import { Route as ConnectorsIndexRouteImport } from './routes/connectors/index'
import { Route as ConnectorsVendorRouteImport } from './routes/connectors/$vendor'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as RunsIdRouteImport } from './routes/runs/$id'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as WorkflowsNameRouteRouteImport } from './routes/workflows/$name/route'
import { Route as ApiRunsIndexRouteImport } from './routes/api/runs/index'
import { Route as WorkflowsNameIndexRouteImport } from './routes/workflows/$name/index'
import { Route as WorkflowsNameNewRouteImport } from './routes/workflows/$name/new'
import { Route as ApiRunsIdIndexRouteImport } from './routes/api/runs/$id/index'
import { Route as WorkflowsNameRunsIdRouteImport } from './routes/workflows/$name/runs/$id'
import { Route as ApiRunsIdApprovalsApprovalIdRouteImport } from './routes/api/runs/$id/approvals/$approvalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRouteRoute = ConnectorsRouteRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRouteRoute = WorkflowsRouteRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiRoute,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ApiRoute,
} as any)
const ApiScenariosRoute = ApiScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => ApiRoute,
} as any)
const ConnectorsIndexRoute = ConnectorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnectorsRouteRoute,
} as any)
const ConnectorsVendorRoute = ConnectorsVendorRouteImport.update({
  id: '/$vendor',
  path: '/$vendor',
  getParentRoute: () => ConnectorsRouteRoute,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkflowsRouteRoute,
} as any)
const WorkflowsNameRouteRoute = WorkflowsNameRouteRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => WorkflowsRouteRoute,
} as any)
const ApiRunsIndexRoute = ApiRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => ApiRoute,
} as any)
const WorkflowsNameIndexRoute = WorkflowsNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkflowsNameRouteRoute,
} as any)
const WorkflowsNameNewRoute = WorkflowsNameNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkflowsNameRouteRoute,
} as any)
const ApiRunsIdIndexRoute = ApiRunsIdIndexRouteImport.update({
  id: '/runs/$id/',
  path: '/runs/$id/',
  getParentRoute: () => ApiRoute,
} as any)
const WorkflowsNameRunsIdRoute = WorkflowsNameRunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => WorkflowsNameRouteRoute,
} as any)
const ApiRunsIdApprovalsApprovalIdRoute =
  ApiRunsIdApprovalsApprovalIdRouteImport.update({
    id: '/runs/$id/approvals/$approvalId',
    path: '/runs/$id/approvals/$approvalId',
    getParentRoute: () => ApiRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRouteRouteWithChildren
  '/workflows': typeof WorkflowsRouteRouteWithChildren
  '/api': typeof ApiRouteWithChildren
  '/inbox': typeof InboxRoute
  '/resources': typeof ResourcesRoute
  '/start': typeof StartRoute
  '/workflows/$name': typeof WorkflowsNameRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/config': typeof ApiConfigRoute
  '/api/scenarios': typeof ApiScenariosRoute
  '/connectors/$vendor': typeof ConnectorsVendorRoute
  '/runs/$id': typeof RunsIdRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/workflows/$name/new': typeof WorkflowsNameNewRoute
  '/api/runs/': typeof ApiRunsIndexRoute
  '/workflows/$name/': typeof WorkflowsNameIndexRoute
  '/workflows/$name/runs/$id': typeof WorkflowsNameRunsIdRoute
  '/api/runs/$id/': typeof ApiRunsIdIndexRoute
  '/api/runs/$id/approvals/$approvalId': typeof ApiRunsIdApprovalsApprovalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/inbox': typeof InboxRoute
  '/resources': typeof ResourcesRoute
  '/start': typeof StartRoute
  '/api/$': typeof ApiSplatRoute
  '/api/config': typeof ApiConfigRoute
  '/api/scenarios': typeof ApiScenariosRoute
  '/connectors/$vendor': typeof ConnectorsVendorRoute
  '/runs/$id': typeof RunsIdRoute
  '/connectors': typeof ConnectorsIndexRoute
  '/runs': typeof RunsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/workflows/$name/new': typeof WorkflowsNameNewRoute
  '/api/runs': typeof ApiRunsIndexRoute
  '/workflows/$name': typeof WorkflowsNameIndexRoute
  '/workflows/$name/runs/$id': typeof WorkflowsNameRunsIdRoute
  '/api/runs/$id': typeof ApiRunsIdIndexRoute
  '/api/runs/$id/approvals/$approvalId': typeof ApiRunsIdApprovalsApprovalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRouteRouteWithChildren
  '/workflows': typeof WorkflowsRouteRouteWithChildren
  '/api': typeof ApiRouteWithChildren
  '/inbox': typeof InboxRoute
  '/resources': typeof ResourcesRoute
  '/start': typeof StartRoute
  '/workflows/$name': typeof WorkflowsNameRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/config': typeof ApiConfigRoute
  '/api/scenarios': typeof ApiScenariosRoute
  '/connectors/$vendor': typeof ConnectorsVendorRoute
  '/runs/$id': typeof RunsIdRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/workflows/$name/new': typeof WorkflowsNameNewRoute
  '/api/runs/': typeof ApiRunsIndexRoute
  '/workflows/$name/': typeof WorkflowsNameIndexRoute
  '/workflows/$name/runs/$id': typeof WorkflowsNameRunsIdRoute
  '/api/runs/$id/': typeof ApiRunsIdIndexRoute
  '/api/runs/$id/approvals/$approvalId': typeof ApiRunsIdApprovalsApprovalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connectors'
    | '/workflows'
    | '/api'
    | '/inbox'
    | '/resources'
    | '/start'
    | '/workflows/$name'
    | '/api/$'
    | '/api/config'
    | '/api/scenarios'
    | '/connectors/$vendor'
    | '/runs/$id'
    | '/connectors/'
    | '/runs/'
    | '/workflows/'
    | '/workflows/$name/new'
    | '/api/runs/'
    | '/workflows/$name/'
    | '/workflows/$name/runs/$id'
    | '/api/runs/$id/'
    | '/api/runs/$id/approvals/$approvalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/inbox'
    | '/resources'
    | '/start'
    | '/api/$'
    | '/api/config'
    | '/api/scenarios'
    | '/connectors/$vendor'
    | '/runs/$id'
    | '/connectors'
    | '/runs'
    | '/workflows'
    | '/workflows/$name/new'
    | '/api/runs'
    | '/workflows/$name'
    | '/workflows/$name/runs/$id'
    | '/api/runs/$id'
    | '/api/runs/$id/approvals/$approvalId'
  id:
    | '__root__'
    | '/'
    | '/connectors'
    | '/workflows'
    | '/api'
    | '/inbox'
    | '/resources'
    | '/start'
    | '/workflows/$name'
    | '/api/$'
    | '/api/config'
    | '/api/scenarios'
    | '/connectors/$vendor'
    | '/runs/$id'
    | '/connectors/'
    | '/runs/'
    | '/workflows/'
    | '/workflows/$name/new'
    | '/api/runs/'
    | '/workflows/$name/'
    | '/workflows/$name/runs/$id'
    | '/api/runs/$id/'
    | '/api/runs/$id/approvals/$approvalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectorsRouteRoute: typeof ConnectorsRouteRouteWithChildren
  WorkflowsRouteRoute: typeof WorkflowsRouteRouteWithChildren
  ApiRoute: typeof ApiRouteWithChildren
  InboxRoute: typeof InboxRoute
  ResourcesRoute: typeof ResourcesRoute
  StartRoute: typeof StartRoute
  RunsIdRoute: typeof RunsIdRoute
  RunsIndexRoute: typeof RunsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/config': {
      id: '/api/config'
      path: '/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/scenarios': {
      id: '/api/scenarios'
      path: '/scenarios'
      fullPath: '/api/scenarios'
      preLoaderRoute: typeof ApiScenariosRouteImport
      parentRoute: typeof ApiRoute
    }
    '/connectors/': {
      id: '/connectors/'
      path: '/'
      fullPath: '/connectors/'
      preLoaderRoute: typeof ConnectorsIndexRouteImport
      parentRoute: typeof ConnectorsRouteRoute
    }
    '/connectors/$vendor': {
      id: '/connectors/$vendor'
      path: '/$vendor'
      fullPath: '/connectors/$vendor'
      preLoaderRoute: typeof ConnectorsVendorRouteImport
      parentRoute: typeof ConnectorsRouteRoute
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof WorkflowsRouteRoute
    }
    '/workflows/$name': {
      id: '/workflows/$name'
      path: '/$name'
      fullPath: '/workflows/$name'
      preLoaderRoute: typeof WorkflowsNameRouteRouteImport
      parentRoute: typeof WorkflowsRouteRoute
    }
    '/api/runs/': {
      id: '/api/runs/'
      path: '/runs'
      fullPath: '/api/runs/'
      preLoaderRoute: typeof ApiRunsIndexRouteImport
      parentRoute: typeof ApiRoute
    }
    '/workflows/$name/': {
      id: '/workflows/$name/'
      path: '/'
      fullPath: '/workflows/$name/'
      preLoaderRoute: typeof WorkflowsNameIndexRouteImport
      parentRoute: typeof WorkflowsNameRouteRoute
    }
    '/workflows/$name/new': {
      id: '/workflows/$name/new'
      path: '/new'
      fullPath: '/workflows/$name/new'
      preLoaderRoute: typeof WorkflowsNameNewRouteImport
      parentRoute: typeof WorkflowsNameRouteRoute
    }
    '/api/runs/$id/': {
      id: '/api/runs/$id/'
      path: '/runs/$id'
      fullPath: '/api/runs/$id/'
      preLoaderRoute: typeof ApiRunsIdIndexRouteImport
      parentRoute: typeof ApiRoute
    }
    '/workflows/$name/runs/$id': {
      id: '/workflows/$name/runs/$id'
      path: '/runs/$id'
      fullPath: '/workflows/$name/runs/$id'
      preLoaderRoute: typeof WorkflowsNameRunsIdRouteImport
      parentRoute: typeof WorkflowsNameRouteRoute
    }
    '/api/runs/$id/approvals/$approvalId': {
      id: '/api/runs/$id/approvals/$approvalId'
      path: '/runs/$id/approvals/$approvalId'
      fullPath: '/api/runs/$id/approvals/$approvalId'
      preLoaderRoute: typeof ApiRunsIdApprovalsApprovalIdRouteImport
      parentRoute: typeof ApiRoute
    }
  }
}

interface ConnectorsRouteRouteChildren {
  ConnectorsVendorRoute: typeof ConnectorsVendorRoute
  ConnectorsIndexRoute: typeof ConnectorsIndexRoute
}

const ConnectorsRouteRouteChildren: ConnectorsRouteRouteChildren = {
  ConnectorsVendorRoute: ConnectorsVendorRoute,
  ConnectorsIndexRoute: ConnectorsIndexRoute,
}

const ConnectorsRouteRouteWithChildren = ConnectorsRouteRoute._addFileChildren(
  ConnectorsRouteRouteChildren,
)

interface WorkflowsNameRouteRouteChildren {
  WorkflowsNameNewRoute: typeof WorkflowsNameNewRoute
  WorkflowsNameIndexRoute: typeof WorkflowsNameIndexRoute
  WorkflowsNameRunsIdRoute: typeof WorkflowsNameRunsIdRoute
}

const WorkflowsNameRouteRouteChildren: WorkflowsNameRouteRouteChildren = {
  WorkflowsNameNewRoute: WorkflowsNameNewRoute,
  WorkflowsNameIndexRoute: WorkflowsNameIndexRoute,
  WorkflowsNameRunsIdRoute: WorkflowsNameRunsIdRoute,
}

const WorkflowsNameRouteRouteWithChildren =
  WorkflowsNameRouteRoute._addFileChildren(WorkflowsNameRouteRouteChildren)

interface WorkflowsRouteRouteChildren {
  WorkflowsNameRouteRoute: typeof WorkflowsNameRouteRouteWithChildren
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

const WorkflowsRouteRouteChildren: WorkflowsRouteRouteChildren = {
  WorkflowsNameRouteRoute: WorkflowsNameRouteRouteWithChildren,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}

const WorkflowsRouteRouteWithChildren = WorkflowsRouteRoute._addFileChildren(
  WorkflowsRouteRouteChildren,
)

interface ApiRouteChildren {
  ApiSplatRoute: typeof ApiSplatRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiScenariosRoute: typeof ApiScenariosRoute
  ApiRunsIndexRoute: typeof ApiRunsIndexRoute
  ApiRunsIdIndexRoute: typeof ApiRunsIdIndexRoute
  ApiRunsIdApprovalsApprovalIdRoute: typeof ApiRunsIdApprovalsApprovalIdRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiSplatRoute: ApiSplatRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiScenariosRoute: ApiScenariosRoute,
  ApiRunsIndexRoute: ApiRunsIndexRoute,
  ApiRunsIdIndexRoute: ApiRunsIdIndexRoute,
  ApiRunsIdApprovalsApprovalIdRoute: ApiRunsIdApprovalsApprovalIdRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectorsRouteRoute: ConnectorsRouteRouteWithChildren,
  WorkflowsRouteRoute: WorkflowsRouteRouteWithChildren,
  ApiRoute: ApiRouteWithChildren,
  InboxRoute: InboxRoute,
  ResourcesRoute: ResourcesRoute,
  StartRoute: StartRoute,
  RunsIdRoute: RunsIdRoute,
  RunsIndexRoute: RunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
