/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as StartRouteImport } from './routes/start'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as RunsIdRouteImport } from './routes/runs/$id'
import { Route as ApiRunsIndexRouteImport } from './routes/api/runs/index'
import { Route as ApiRunsIdIndexRouteImport } from './routes/api/runs/$id/index'
import { Route as ApiRunsIdApprovalsApprovalIdRouteImport } from './routes/api/runs/$id/approvals/$approvalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsIndexRoute = ApiRunsIndexRouteImport.update({
  id: '/api/runs/',
  path: '/api/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsIdIndexRoute = ApiRunsIdIndexRouteImport.update({
  id: '/api/runs/$id/',
  path: '/api/runs/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsIdApprovalsApprovalIdRoute =
  ApiRunsIdApprovalsApprovalIdRouteImport.update({
    id: '/api/runs/$id/approvals/$approvalId',
    path: '/api/runs/$id/approvals/$approvalId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/start': typeof StartRoute
  '/workflows': typeof WorkflowsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/config': typeof ApiConfigRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs/': typeof RunsIndexRoute
  '/api/runs/': typeof ApiRunsIndexRoute
  '/api/runs/$id/': typeof ApiRunsIdIndexRoute
  '/api/runs/$id/approvals/$approvalId': typeof ApiRunsIdApprovalsApprovalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/start': typeof StartRoute
  '/workflows': typeof WorkflowsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/config': typeof ApiConfigRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs': typeof RunsIndexRoute
  '/api/runs': typeof ApiRunsIndexRoute
  '/api/runs/$id': typeof ApiRunsIdIndexRoute
  '/api/runs/$id/approvals/$approvalId': typeof ApiRunsIdApprovalsApprovalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inbox': typeof InboxRoute
  '/start': typeof StartRoute
  '/workflows': typeof WorkflowsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/config': typeof ApiConfigRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs/': typeof RunsIndexRoute
  '/api/runs/': typeof ApiRunsIndexRoute
  '/api/runs/$id/': typeof ApiRunsIdIndexRoute
  '/api/runs/$id/approvals/$approvalId': typeof ApiRunsIdApprovalsApprovalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inbox'
    | '/start'
    | '/workflows'
    | '/api/$'
    | '/api/config'
    | '/runs/$id'
    | '/runs/'
    | '/api/runs/'
    | '/api/runs/$id/'
    | '/api/runs/$id/approvals/$approvalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inbox'
    | '/start'
    | '/workflows'
    | '/api/$'
    | '/api/config'
    | '/runs/$id'
    | '/runs'
    | '/api/runs'
    | '/api/runs/$id'
    | '/api/runs/$id/approvals/$approvalId'
  id:
    | '__root__'
    | '/'
    | '/inbox'
    | '/start'
    | '/workflows'
    | '/api/$'
    | '/api/config'
    | '/runs/$id'
    | '/runs/'
    | '/api/runs/'
    | '/api/runs/$id/'
    | '/api/runs/$id/approvals/$approvalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InboxRoute: typeof InboxRoute
  StartRoute: typeof StartRoute
  WorkflowsRoute: typeof WorkflowsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiConfigRoute: typeof ApiConfigRoute
  RunsIdRoute: typeof RunsIdRoute
  RunsIndexRoute: typeof RunsIndexRoute
  ApiRunsIndexRoute: typeof ApiRunsIndexRoute
  ApiRunsIdIndexRoute: typeof ApiRunsIdIndexRoute
  ApiRunsIdApprovalsApprovalIdRoute: typeof ApiRunsIdApprovalsApprovalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/': {
      id: '/api/runs/'
      path: '/api/runs'
      fullPath: '/api/runs/'
      preLoaderRoute: typeof ApiRunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/$id/': {
      id: '/api/runs/$id/'
      path: '/api/runs/$id'
      fullPath: '/api/runs/$id/'
      preLoaderRoute: typeof ApiRunsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/$id/approvals/$approvalId': {
      id: '/api/runs/$id/approvals/$approvalId'
      path: '/api/runs/$id/approvals/$approvalId'
      fullPath: '/api/runs/$id/approvals/$approvalId'
      preLoaderRoute: typeof ApiRunsIdApprovalsApprovalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InboxRoute: InboxRoute,
  StartRoute: StartRoute,
  WorkflowsRoute: WorkflowsRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiConfigRoute: ApiConfigRoute,
  RunsIdRoute: RunsIdRoute,
  RunsIndexRoute: RunsIndexRoute,
  ApiRunsIndexRoute: ApiRunsIndexRoute,
  ApiRunsIdIndexRoute: ApiRunsIdIndexRoute,
  ApiRunsIdApprovalsApprovalIdRoute: ApiRunsIdApprovalsApprovalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
