import type { ResourceFields } from "../resource.ts";
import { ctyToZod, key } from "./ctyToZod.ts";
import type {
  ResourcesConfig,
  TfAttribute,
  TfBlock,
  TfBlockShape,
  TfNestedBlock,
  TfNestedType,
  TfSchemaDocument,
  TfShape,
} from "./types.ts";

/** A description that says the attribute cannot change in place. */
const FORCES_NEW = /forces? (?:a )?new resource|requires? replacement/i;

/** Where `resources.gen.ts` came from, for its header: paths relative to the connector. */
export interface GenerateSources {
  schema: string;
  config: string;
}

/**
 * The source of a connector's `resources.gen.ts`: for each type `config.types` names, its zod
 * schema in the resource's shape, its flagged fields and its state layout. Pure: the same
 * document and config give the same text, so a regenerated file on a clean tree is no change.
 */
export function generateResources(doc: TfSchemaDocument, config: ResourcesConfig, sources: GenerateSources): string {
  const unknown = config.types.filter((t) => !Object.hasOwn(doc.resources, t));
  if (unknown.length) throw new Error(`${doc.source} ${doc.version} has no resource type ${unknown.join(", ")}`);
  for (const [type, names] of Object.entries(config.immutable ?? {})) {
    if (!config.types.includes(type)) throw new Error(`immutable names ${type}, which \`types\` does not list`);
    const block = doc.resources[type]!.block;
    const missing = names.filter((n) => !Object.hasOwn(block.attributes, n) && !Object.hasOwn(block.blocks ?? {}, n));
    if (missing.length) throw new Error(`immutable: ${type} has no attribute ${missing.join(", ")}`);
  }

  const provider = {
    source: doc.source,
    version: doc.version,
    protocol: doc.protocol,
    ...(config.sha256 === undefined ? {} : { sha256: config.sha256 }),
  };
  const out = [
    `// Generated by \`pnpm generate\` (packages/workflows/src/tfschema) from ${sources.schema}`,
    `// and ${sources.config}. Do not edit: change the config and run \`pnpm generate\` again.`,
    `import type { TfProvider, TfResourceType } from "@sanoma/workflows/tfschema";`,
    `import { z } from "zod";`,
    ``,
    `/** The OpenTofu provider these types are from. */`,
    `export const provider: TfProvider = ${literal(provider, "")};`,
  ];
  for (const type of config.types.toSorted()) {
    const { schemaVersion, block } = doc.resources[type]!;
    const fields = fieldsOf(block, config.immutable?.[type] ?? []);
    out.push(
      ``,
      ...docComment(block.description, ""),
      `export const ${type} = {`,
      `  typeName: ${JSON.stringify(type)},`,
      `  schemaVersion: ${schemaVersion},`,
      `  schema: ${blockSchema(block, "  ")},`,
      `  fields: ${literal(fields, "  ")},`,
      `  shape: ${literal(shapeOf(block), "  ")},`,
      `} satisfies TfResourceType;`,
    );
  }
  return `${out.join("\n")}\n`;
}

/** `z.object({ … })` for a block: its attributes, then its nested blocks. */
function blockSchema(block: TfBlock, indent: string): string {
  const inner = `${indent}  `;
  const lines = [
    ...Object.entries(block.attributes).map(([name, a]) => `${inner}${key(name)}: ${attributeSchema(a, inner)},`),
    ...Object.entries(block.blocks ?? {}).map(([name, b]) => `${inner}${key(name)}: ${nestedBlockSchema(b, inner)},`),
  ];
  return lines.length ? `z.object({\n${lines.join("\n")}\n${indent}})` : "z.object({})";
}

function attributeSchema(a: TfAttribute, indent: string): string {
  const base = a.nestedType ? nestedTypeSchema(a.nestedType, indent) : ctyToZod(a.type);
  return annotate(a.required ? base : `${base}.nullish()`, a.description, a.deprecated);
}

/** A nested attribute (protocol 6), with each child's own flags: required children stay required. */
function nestedTypeSchema(nested: TfNestedType, indent: string): string {
  const object = blockSchema({ attributes: nested.attributes }, indent);
  switch (nested.nesting) {
    case "single":
      return object;
    case "list":
    case "set":
      return `z.array(${object})`;
    case "map":
      return `z.record(z.string(), ${object})`;
  }
}

/**
 * A nested block: an object for `single` and `group`, and for a list or set of at most one
 * (SDKv2's way of saying "one object"); an array for other lists and sets; a record for `map`.
 * It may be left out unless the provider requires at least one.
 */
function nestedBlockSchema(b: TfNestedBlock, indent: string): string {
  const object = blockSchema(b.block, indent);
  const required = (b.minItems ?? 0) > 0;
  let base: string;
  if (b.nesting === "map") base = `z.record(z.string(), ${object})`;
  else if (b.nesting === "single" || b.nesting === "group" || isOne(b)) base = object;
  else base = `z.array(${object})${required ? `.min(${b.minItems})` : ""}`;
  return annotate(required ? base : `${base}.nullish()`, b.block.description, b.block.deprecated);
}

const isOne = (b: TfNestedBlock) => (b.nesting === "list" || b.nesting === "set") && b.maxItems === 1;

/** The description, as `.describe()`, and `deprecated` in the schema's metadata, which keeps the description. */
function annotate(zod: string, description: string | undefined, deprecated: boolean | undefined): string {
  const text = description?.trim();
  const described = text ? `${zod}.describe(${JSON.stringify(text)})` : zod;
  return deprecated ? `${described}.meta({ deprecated: true })` : described;
}

/** True when the attribute, or anything nested in it, is sensitive or write-only. */
const isSecret = (a: TfAttribute): boolean =>
  Boolean(a.sensitive || a.writeOnly || Object.values(a.nestedType?.attributes ?? {}).some(isSecret));

/** The flagged fields of a block, by dotted path: `vendorOwned`, `writeOnly` and `immutable`. */
function fieldsOf(block: TfBlock, immutable: string[]): ResourceFields {
  const fields = { immutable: new Set(immutable), vendorOwned: [] as string[], writeOnly: [] as string[] };
  const walk = (attributes: Record<string, TfAttribute>, blocks: Record<string, TfNestedBlock>, prefix: string) => {
    for (const [name, a] of Object.entries(attributes)) {
      const path = prefix + name;
      if (a.computed && !a.optional && !a.required) fields.vendorOwned.push(path);
      if (isSecret(a)) fields.writeOnly.push(path);
      else if (a.nestedType) walk(a.nestedType.attributes, {}, `${path}.`);
      if (FORCES_NEW.test(a.description ?? "")) fields.immutable.add(path);
    }
    for (const [name, b] of Object.entries(blocks)) walk(b.block.attributes, b.block.blocks ?? {}, `${prefix + name}.`);
  };
  walk(block.attributes, block.blocks ?? {}, "");
  return { ...fields, immutable: [...fields.immutable].toSorted() };
}

/** The state layout of a block, for `fromTfState` and `toTfState`. */
function shapeOf(block: TfBlock): TfShape {
  const attributes = Object.keys(block.attributes);
  const secret = attributes.filter((name) => isSecret(block.attributes[name]!));
  const blocks = Object.entries(block.blocks ?? {}).map(([name, b]): [string, TfBlockShape] => [
    name,
    { nesting: b.nesting, ...(isOne(b) && { one: true }), shape: shapeOf(b.block) },
  ]);
  return {
    attributes,
    ...(secret.length > 0 && { secret }),
    ...(blocks.length > 0 && { blocks: Object.fromEntries(blocks) }),
  };
}

/** A value as TypeScript source, indented to sit at `indent`. */
const literal = (value: unknown, indent: string) => JSON.stringify(value, null, 2).replaceAll("\n", `\n${indent}`);

/** A JSDoc comment of the description's first paragraph, or nothing. */
function docComment(description: string | undefined, indent: string): string[] {
  const text = description
    ?.trim()
    .split(/\n\s*\n/)[0]
    ?.replaceAll("*/", "*\\/");
  if (!text) return [];
  return [`${indent}/**`, ...text.split("\n").map((line) => `${indent} * ${line.trim()}`.trimEnd()), `${indent} */`];
}
