import { defineDriver, DriverError, retryableStatus, type CallContext } from "@sanoma/workflows";
import { z } from "zod";
import { resend } from "./index.ts";
// Generated by `pnpm run generate` (openapi-ts.config.ts); never edited by hand.
import { client as generated } from "./generated/client.gen.ts";
import { createClient } from "./generated/client/index.ts";
import { broadcastsCreate, broadcastsGet, broadcastsSend } from "./generated/index.ts";

export interface ResendDriverOptions {
  /** The sender of a broadcast whose input has no `from`. Resend requires one. */
  from?: string;
  /** How long one request may take before it fails, retryable. Default 15 seconds. */
  timeoutMs?: number;
}

/** Resend's error body. The spec declares none; the docs give `{ statusCode, name, message }`. */
const errorBody = z.object({ name: z.string().optional(), message: z.string().optional() }).catch({});

/** The error for a request that got no reply (a timeout, a dropped connection): it may be tried again. */
function noReply(op: string, timeoutMs: number, cause: unknown): DriverError {
  const timedOut = cause instanceof DOMException && cause.name === "TimeoutError";
  return new DriverError(`resend: ${op} ${timedOut ? `timed out after ${timeoutMs} ms` : "got no reply"}`, {
    retryable: true,
    cause,
  });
}

/**
 * The DriverError for a request that failed: the client hands its error interceptor what went
 * wrong and, when Resend answered, the response. Its `fetch` turns a missing reply into one
 * already, so an error with no response was thrown before the request was sent.
 */
function failure(op: string, timeoutMs: number) {
  return (error: unknown, response: Response | undefined): DriverError => {
    if (error instanceof DriverError) return error;
    if (!response) {
      return new DriverError(`resend: ${op} could not build its request`, { retryable: false, cause: error });
    }
    const { ok, status, statusText } = response;
    // The body could not be read: the timeout fired, or the reply was cut off. Either may be tried again.
    const unread = error instanceof Error && !(error instanceof SyntaxError);
    if (unread && (error as Error).name === "TimeoutError") return noReply(op, timeoutMs, error);
    if (ok) {
      // A 2xx whose body is not JSON is no answer to retry; one cut off is.
      return new DriverError(
        `resend: ${op} replied ${status} with ${unread ? "a body cut off" : "a body that is not JSON"}`,
        {
          retryable: unread,
          status,
          cause: error,
        },
      );
    }
    const { name, message } = unread ? {} : errorBody.parse(error);
    // A daily or monthly quota does not lift in the seconds a retry waits; a 409
    // `concurrent_idempotent_requests` is another request with this key still in flight.
    const retryable =
      (retryableStatus(status) && !name?.endsWith("_quota_exceeded")) ||
      (status === 409 && name === "concurrent_idempotent_requests");
    return new DriverError(`resend: ${op} failed (${status}): ${message ?? statusText}`, {
      retryable,
      status,
      ...(name === undefined ? {} : { vendorCode: name }),
    });
  };
}

/** The broadcast in a reply Resend accepted: the spec leaves its id optional, and a proxy may answer instead. */
function broadcastOf<T extends { id?: string }>(
  op: string,
  reply: { data: T; response: Response },
): T & { id: string } {
  const { data } = reply;
  if (typeof data === "object" && data !== null && data.id) return data as T & { id: string };
  const { status } = reply.response;
  throw new DriverError(`resend: ${op} replied ${status} without a broadcast id`, { retryable: false, status });
}

/**
 * Calls Resend's Broadcasts API with the key in `RESEND_API_KEY`, read on every call. The
 * contract's `audience` is Resend's `segment_id`: Resend renamed audiences to segments.
 */
export function resendDriver(options: ResendDriverOptions = {}) {
  const timeoutMs = options.timeoutMs ?? 15_000;

  function client(op: string, call: CallContext) {
    const key = process.env.RESEND_API_KEY;
    if (!key) throw new DriverError("resend: RESEND_API_KEY is not set", { retryable: false });
    // The generated client's config (the spec's server, throwOnError), with this call's key and headers.
    const api = createClient({
      ...generated.getConfig(),
      auth: key,
      // Resend documents Idempotency-Key for emails only; it is sent in case broadcasts honour it too.
      headers: { "Idempotency-Key": call.idempotencyKey },
      fetch: (input, init) =>
        fetch(input, { ...init, signal: AbortSignal.timeout(timeoutMs) }).catch((cause: unknown) => {
          throw noReply(op, timeoutMs, cause);
        }),
    });
    api.interceptors.error.use(failure(op, timeoutMs));
    return api;
  }

  return defineDriver(resend, {
    broadcast: {
      create: async (input, call) => {
        const from = input.from ?? options.from;
        if (!from) {
          throw new DriverError("resend: broadcast.create needs `from` in its input or resendDriver({ from })", {
            retryable: false,
          });
        }
        const reply = await broadcastsCreate({
          client: client("broadcast.create", call),
          // `name` shows in Resend's dashboard only: it ties the broadcast to the call that made it.
          body: {
            segment_id: input.audience,
            from,
            subject: input.subject,
            html: input.html,
            name: call.idempotencyKey,
          },
        });
        return { id: broadcastOf("broadcast.create", reply).id };
      },
      send: async ({ id }, call) => {
        const api = client("broadcast.send", call);
        // A replay of a send whose reply was lost must not send again: send only a broadcast that
        // is still a draft or scheduled, and otherwise say where it is.
        const { status } = broadcastOf("broadcast.send", await broadcastsGet({ client: api, path: { id } }));
        if (status === "sent") return { id, status: "sent" as const };
        if (status === "queued") return { id, status: "queued" as const };
        if (status !== "draft" && status !== "scheduled") {
          throw new DriverError(
            `resend: broadcast.send: broadcast ${id} is ${status ?? "of no status"}, not sendable`,
            {
              retryable: false,
            },
          );
        }
        const reply = await broadcastsSend({ client: api, path: { id }, body: {} });
        // Resend replies with the id only: it accepts the broadcast and sends it in the background.
        return { id: broadcastOf("broadcast.send", reply).id, status: "queued" as const };
      },
    },
  });
}
