import { defineDriver, DriverError, type CallContext } from "@sanoma/workflows";
import createClient from "openapi-fetch";
import { z } from "zod";
import { resend } from "./index.ts";
// Generated by `pnpm run generate` from Resend's OpenAPI spec, cut to these two operations
// (openapi.redocly.yaml), pinned to
// https://github.com/resend/resend-openapi/blob/8916b099d7f52b8552a2e1ef38a7f16fcd17864c/resend.yaml
import type { paths } from "./resend-api.d.ts";

export interface ResendDriverOptions {
  /** The sender of a broadcast whose input has no `from`. Resend requires one. */
  from?: string;
  /** How long one request may take before it fails, retryable. Default 15 seconds. */
  timeoutMs?: number;
}

/** Resend's error body. The spec declares none; the docs give `{ statusCode, name, message }`. */
const errorBody = z.object({ name: z.string().optional(), message: z.string().optional() }).catch({});

/** The broadcast id from Resend's reply, or the DriverError its status and body say. */
function idOf(op: string, reply: { data?: { id?: string }; error?: unknown; response: Response }): string {
  const { ok, status, statusText } = reply.response;
  if (ok && reply.data?.id) return reply.data.id;
  if (ok) throw new DriverError(`resend: ${op} replied ${status} without a broadcast id`, { retryable: false, status });
  const { name, message } = errorBody.parse(reply.error);
  // A daily or monthly quota does not lift in the seconds a retry waits.
  const retryable = status >= 500 || (status === 429 && !name?.endsWith("_quota_exceeded"));
  throw new DriverError(`resend: ${op} failed (${status}): ${message ?? statusText}`, {
    retryable,
    status,
    ...(name === undefined ? {} : { vendorCode: name }),
  });
}

/**
 * Calls Resend's Broadcasts API with the key in `RESEND_API_KEY`, read on every call. The
 * contract's `audience` is Resend's `segment_id`: Resend renamed audiences to segments.
 */
export function resendDriver(options: ResendDriverOptions = {}) {
  const timeoutMs = options.timeoutMs ?? 15_000;

  function client(op: string, call: CallContext) {
    const key = process.env.RESEND_API_KEY;
    if (!key) throw new DriverError("resend: RESEND_API_KEY is not set", { retryable: false });
    return createClient<paths>({
      baseUrl: "https://api.resend.com",
      // Resend documents Idempotency-Key for emails only; it is sent in case broadcasts honour it too.
      headers: { Authorization: `Bearer ${key}`, "Idempotency-Key": call.idempotencyKey },
      // No reply at all (a timeout, a dropped connection): the call may be tried again.
      fetch: (req) =>
        fetch(req, { signal: AbortSignal.timeout(timeoutMs) }).catch((cause: unknown) => {
          const timedOut = cause instanceof DOMException && cause.name === "TimeoutError";
          throw new DriverError(`resend: ${op} ${timedOut ? `timed out after ${timeoutMs} ms` : "got no reply"}`, {
            retryable: true,
            cause,
          });
        }),
    });
  }

  return defineDriver(resend, {
    broadcast: {
      create: async (input, call) => {
        const from = input.from ?? options.from;
        if (!from) {
          throw new DriverError("resend: broadcast.create needs `from` in its input or resendDriver({ from })", {
            retryable: false,
          });
        }
        const reply = await client("broadcast.create", call).POST("/broadcasts", {
          // `name` shows in Resend's dashboard only: it ties the broadcast to the call that made it.
          body: {
            segment_id: input.audience,
            from,
            subject: input.subject,
            html: input.html,
            name: call.idempotencyKey,
          },
        });
        return { id: idOf("broadcast.create", reply) };
      },
      send: async ({ id }, call) => {
        const reply = await client("broadcast.send", call).POST("/broadcasts/{id}/send", {
          params: { path: { id } },
          body: {},
        });
        // Resend replies with the id only: it accepts the broadcast and sends it in the background.
        return { id: idOf("broadcast.send", reply), status: "queued" as const };
      },
    },
  });
}
