/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/broadcasts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a broadcast */
    post: operations["broadcasts/create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/broadcasts/{id}/send": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Send or schedule a broadcast */
    post: operations["broadcasts/send"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateBroadcastOptions: {
      /** @description Name of the broadcast. */
      name?: string;
      /** @description Unique identifier of the segment this broadcast will be sent to. */
      segment_id: string;
      /**
       * @deprecated
       * @description Use `segment_id` instead. Unique identifier of the segment this broadcast will be sent to.
       */
      audience_id?: string;
      /** @description The email address of the sender. */
      from: string;
      /** @description The subject line of the email. */
      subject: string;
      /** @description The email addresses to which replies should be sent. */
      reply_to?: string[];
      /**
       * @description The preview text of the email.
       * @example Here are our announcements
       */
      preview_text?: string;
      /** @description The HTML version of the message. */
      html?: string;
      /** @description The plain text version of the message. */
      text?: string;
      /** @description The topic ID that the broadcast will be scoped to. */
      topic_id?: string;
      /** @description Whether to send the broadcast immediately or keep it as a draft. */
      send?: boolean;
      /** @description Schedule time to send the broadcast. Can only be used if `send` is true. */
      scheduled_at?: string;
    };
    CreateBroadcastResponseSuccess: {
      /**
       * @description The ID of the broadcast.
       * @example 78261eea-8f8b-4381-83c6-79fa7120f1cf
       */
      id?: string;
      /**
       * @description The object type of the response.
       * @example broadcast
       */
      object?: string;
    };
    SendBroadcastOptions: {
      /** @description Schedule email to be sent later. The date should be in ISO 8601 format. */
      scheduled_at?: string;
    };
    SendBroadcastResponseSuccess: {
      /**
       * @description The ID of the broadcast.
       * @example 78261eea-8f8b-4381-83c6-79fa7120f1cf
       */
      id?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  "broadcasts/create": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["CreateBroadcastOptions"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateBroadcastResponseSuccess"];
        };
      };
    };
  };
  "broadcasts/send": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The Broadcast ID. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["SendBroadcastOptions"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SendBroadcastResponseSuccess"];
        };
      };
    };
  };
}
