// Generated by `pnpm generate` (packages/workflows/src/tfschema) from testdata/schemas/stripe_stripe_0.3.0.json
// and src/resources.config.ts. Do not edit: change the config and run `pnpm generate` again.
import type { TfProvider, TfResourceType } from "@sanoma/workflows/tfschema";
import { z } from "zod";

/** The OpenTofu provider these types are from. */
export const provider: TfProvider = {
  source: "stripe/stripe",
  version: "0.3.0",
  protocol: 6,
  sha256: "2e3ae569e1bee7c64ae7f10e6ceaaf5bfab4db7af38979bab28f9b7a35a260c5",
};

/**
 * Products describe the specific goods or services you offer to your customers.
 * For example, you might offer a Standard and Premium version of your goods or service; each version would be a separate Product.
 * They can be used in conjunction with [Prices](https://api.stripe.com#prices) to configure pricing in Payment Links, Checkout, and Subscriptions.
 */
export const stripe_product = {
  typeName: "stripe_product",
  schemaVersion: 2,
  schema: z.object({
    active: z.boolean().nullish().describe("Whether the product is currently available for purchase."),
    created: z
      .number()
      .nullish()
      .describe("Time at which the object was created. Measured in seconds since the Unix epoch."),
    default_price: z
      .string()
      .nullish()
      .describe(
        "The ID of the [Price](https://docs.stripe.com/api/prices) object that is the default price for this product.",
      ),
    description: z
      .string()
      .nullish()
      .describe(
        "The product's description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.",
      ),
    id: z.string().nullish().describe("Unique identifier for the object."),
    images: z
      .array(z.string())
      .nullish()
      .describe("A list of up to 8 URLs of images for this product, meant to be displayable to the customer."),
    livemode: z
      .boolean()
      .nullish()
      .describe(
        "If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.",
      ),
    metadata: z
      .record(z.string(), z.string())
      .nullish()
      .describe(
        "Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.",
      ),
    name: z.string().describe("The product's name, meant to be displayable to the customer."),
    object: z
      .string()
      .nullish()
      .describe("String representing the object's type. Objects of the same type share the same value."),
    shippable: z.boolean().nullish().describe("Whether this product is shipped (i.e., physical goods)."),
    statement_descriptor: z
      .string()
      .nullish()
      .describe(
        "Extra information about a product which will appear on your customer's credit card statement. In the case that multiple products are billed at once, the first statement descriptor will be used. Only used for subscription payments.",
      ),
    tax_code: z.string().nullish().describe("A [tax code](https://docs.stripe.com/tax/tax-categories) ID."),
    type: z
      .string()
      .nullish()
      .describe(
        "The type of the product. The product is either of type `good`, which is eligible for use with Orders and SKUs, or `service`, which is eligible for use with Subscriptions and Plans.",
      ),
    unit_label: z
      .string()
      .nullish()
      .describe(
        "A label that represents units of this product. When set, this will be included in customers' receipts, invoices, Checkout, and the customer portal.",
      ),
    updated: z
      .number()
      .nullish()
      .describe("Time at which the object was last updated. Measured in seconds since the Unix epoch."),
    url: z.string().nullish().describe("A URL of a publicly-accessible webpage for this product."),
    default_price_data: z
      .array(
        z.object({
          currency: z
            .string()
            .describe(
              "Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).",
            ),
          metadata: z
            .record(z.string(), z.string())
            .nullish()
            .describe(
              "Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.",
            ),
          tax_behavior: z
            .string()
            .nullish()
            .describe(
              "Only required if a [default tax behavior](https://docs.stripe.com/tax/products-prices-tax-categories-tax-behavior#setting-a-default-tax-behavior-(recommended)) was not provided in the Stripe Tax settings. Specifies whether the price is considered inclusive of taxes or exclusive of taxes. One of `inclusive`, `exclusive`, or `unspecified`. Once specified as either `inclusive` or `exclusive`, it cannot be changed.",
            ),
          unit_amount: z
            .number()
            .nullish()
            .describe(
              "A positive integer in cents (or local equivalent) (or 0 for a free price) representing how much to charge. One of `unit_amount`, `unit_amount_decimal`, or `custom_unit_amount` is required.",
            ),
          unit_amount_decimal: z
            .string()
            .nullish()
            .describe(
              "Same as `unit_amount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places. Only one of `unit_amount` and `unit_amount_decimal` can be set.",
            ),
          currency_options: z
            .array(
              z.object({
                key: z.string().describe("Key for this entry."),
                tax_behavior: z
                  .string()
                  .nullish()
                  .describe(
                    "Only required if a [default tax behavior](https://docs.stripe.com/tax/products-prices-tax-categories-tax-behavior#setting-a-default-tax-behavior-(recommended)) was not provided in the Stripe Tax settings. Specifies whether the price is considered inclusive of taxes or exclusive of taxes. One of `inclusive`, `exclusive`, or `unspecified`. Once specified as either `inclusive` or `exclusive`, it cannot be changed.",
                  ),
                tiers: z
                  .array(
                    z.object({
                      flat_amount: z
                        .number()
                        .nullish()
                        .describe(
                          "The flat billing amount for an entire tier, regardless of the number of units in the tier.",
                        ),
                      flat_amount_decimal: z
                        .string()
                        .nullish()
                        .describe(
                          "Same as `flat_amount`, but accepts a decimal value representing an integer in the minor units of the currency. Only one of `flat_amount` and `flat_amount_decimal` can be set.",
                        ),
                      unit_amount: z
                        .number()
                        .nullish()
                        .describe("The per unit billing amount for each individual unit for which this tier applies."),
                      unit_amount_decimal: z
                        .string()
                        .nullish()
                        .describe(
                          "Same as `unit_amount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places. Only one of `unit_amount` and `unit_amount_decimal` can be set.",
                        ),
                      up_to: z
                        .number()
                        .describe(
                          "Specifies the upper bound of this tier. The lower bound of a tier is the upper bound of the previous tier adding one. Use `inf` to define a fallback tier.",
                        ),
                    }),
                  )
                  .nullish()
                  .describe(
                    "Each element represents a pricing tier. This parameter requires `billing_scheme` to be set to `tiered`. See also the documentation for `billing_scheme`.",
                  ),
                unit_amount: z
                  .number()
                  .nullish()
                  .describe(
                    "A positive integer in cents (or local equivalent) (or 0 for a free price) representing how much to charge.",
                  ),
                unit_amount_decimal: z
                  .string()
                  .nullish()
                  .describe(
                    "Same as `unit_amount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places. Only one of `unit_amount` and `unit_amount_decimal` can be set.",
                  ),
                custom_unit_amount: z
                  .array(
                    z.object({
                      enabled: z
                        .boolean()
                        .describe(
                          "Pass in `true` to enable `custom_unit_amount`, otherwise omit `custom_unit_amount`.",
                        ),
                      maximum: z
                        .number()
                        .nullish()
                        .describe("The maximum unit amount the customer can specify for this item."),
                      minimum: z
                        .number()
                        .nullish()
                        .describe(
                          "The minimum unit amount the customer can specify for this item. Must be at least the minimum charge amount.",
                        ),
                      preset: z
                        .number()
                        .nullish()
                        .describe("The starting unit amount which can be updated by the customer."),
                    }),
                  )
                  .nullish()
                  .describe(
                    "When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Links.",
                  ),
              }),
            )
            .nullish()
            .describe(
              "Prices defined in each available currency option. Each key must be a three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) and a [supported currency](https://stripe.com/docs/currencies).",
            ),
          custom_unit_amount: z
            .array(
              z.object({
                enabled: z
                  .boolean()
                  .describe("Pass in `true` to enable `custom_unit_amount`, otherwise omit `custom_unit_amount`."),
                maximum: z
                  .number()
                  .nullish()
                  .describe("The maximum unit amount the customer can specify for this item."),
                minimum: z
                  .number()
                  .nullish()
                  .describe(
                    "The minimum unit amount the customer can specify for this item. Must be at least the minimum charge amount.",
                  ),
                preset: z.number().nullish().describe("The starting unit amount which can be updated by the customer."),
              }),
            )
            .nullish()
            .describe(
              "When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Links.",
            ),
          recurring: z
            .array(
              z.object({
                interval: z.string().describe("Specifies billing frequency. Either `day`, `week`, `month` or `year`."),
                interval_count: z
                  .number()
                  .nullish()
                  .describe(
                    "The number of intervals between subscription billings. For example, `interval=month` and `interval_count=3` bills every 3 months. Maximum of three years interval allowed (3 years, 36 months, or 156 weeks).",
                  ),
              }),
            )
            .nullish()
            .describe("The recurring components of a price such as `interval` and `interval_count`."),
        }),
      )
      .nullish()
      .describe(
        "Data used to generate a new [Price](https://docs.stripe.com/api/prices) object. This Price will be set as the default price for this product.",
      ),
    marketing_features: z
      .array(
        z.object({
          name: z.string().describe("The marketing feature name. Up to 80 characters long."),
        }),
      )
      .nullish()
      .describe(
        "A list of up to 15 marketing features for this product. These are displayed in [pricing tables](https://docs.stripe.com/payments/checkout/pricing-table).",
      ),
    package_dimensions: z
      .array(
        z.object({
          height: z.number().describe("Height, in inches."),
          length: z.number().describe("Length, in inches."),
          weight: z.number().describe("Weight, in ounces."),
          width: z.number().describe("Width, in inches."),
        }),
      )
      .nullish()
      .describe("The dimensions of this product for shipping purposes."),
  }),
  fields: {
    immutable: [],
    vendorOwned: ["created", "default_price", "id", "livemode", "object", "updated"],
    writeOnly: [],
  },
  shape: {
    attributes: [
      "active",
      "created",
      "default_price",
      "description",
      "id",
      "images",
      "livemode",
      "metadata",
      "name",
      "object",
      "shippable",
      "statement_descriptor",
      "tax_code",
      "type",
      "unit_label",
      "updated",
      "url",
    ],
    blocks: {
      default_price_data: {
        nesting: "list",
        shape: {
          attributes: ["currency", "metadata", "tax_behavior", "unit_amount", "unit_amount_decimal"],
          blocks: {
            currency_options: {
              nesting: "list",
              shape: {
                attributes: ["key", "tax_behavior", "tiers", "unit_amount", "unit_amount_decimal"],
                blocks: {
                  custom_unit_amount: {
                    nesting: "list",
                    shape: {
                      attributes: ["enabled", "maximum", "minimum", "preset"],
                    },
                  },
                },
              },
            },
            custom_unit_amount: {
              nesting: "list",
              shape: {
                attributes: ["enabled", "maximum", "minimum", "preset"],
              },
            },
            recurring: {
              nesting: "list",
              shape: {
                attributes: ["interval", "interval_count"],
              },
            },
          },
        },
      },
      marketing_features: {
        nesting: "list",
        shape: {
          attributes: ["name"],
        },
      },
      package_dimensions: {
        nesting: "list",
        shape: {
          attributes: ["height", "length", "weight", "width"],
        },
      },
    },
  },
} satisfies TfResourceType;

/**
 * You can configure [webhook endpoints](https://docs.stripe.com/webhooks/) via the API to be
 * notified about events that happen in your Stripe account or connected
 * accounts.
 */
export const stripe_webhook_endpoint = {
  typeName: "stripe_webhook_endpoint",
  schemaVersion: 1,
  schema: z.object({
    api_version: z.string().nullish().describe("The API version events are rendered as for this webhook endpoint."),
    application: z.string().nullish().describe("The ID of the associated Connect application."),
    connect: z
      .boolean()
      .nullish()
      .describe(
        "Whether this endpoint should receive events from connected accounts (`true`), or from your account (`false`). Defaults to `false`.",
      ),
    created: z
      .number()
      .nullish()
      .describe("Time at which the object was created. Measured in seconds since the Unix epoch."),
    description: z.string().nullish().describe("An optional description of what the webhook is used for."),
    enabled_events: z
      .array(z.string())
      .describe(
        "The list of events to enable for this endpoint. `['*']` indicates that all events are enabled, except those that require explicit selection.",
      ),
    id: z.string().nullish().describe("Unique identifier for the object."),
    livemode: z
      .boolean()
      .nullish()
      .describe(
        "If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.",
      ),
    metadata: z
      .record(z.string(), z.string())
      .nullish()
      .describe(
        "Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.",
      ),
    object: z
      .string()
      .nullish()
      .describe("String representing the object's type. Objects of the same type share the same value."),
    secret: z
      .string()
      .nullish()
      .describe(
        "The endpoint's secret, used to generate [webhook signatures](https://docs.stripe.com/webhooks/signatures). Only returned at creation.",
      ),
    status: z.string().nullish().describe("The status of the webhook. It can be `enabled` or `disabled`."),
    url: z.string().describe("The URL of the webhook endpoint."),
  }),
  fields: {
    immutable: ["api_version", "connect"],
    vendorOwned: ["application", "created", "id", "livemode", "object", "secret", "status"],
    writeOnly: ["secret"],
  },
  shape: {
    attributes: [
      "api_version",
      "application",
      "connect",
      "created",
      "description",
      "enabled_events",
      "id",
      "livemode",
      "metadata",
      "object",
      "secret",
      "status",
      "url",
    ],
    secret: ["secret"],
  },
} satisfies TfResourceType;
