// Generated by `pnpm generate` (@sanoma/bridge/tfschema) from the integrations/github 6.13.0 schema
// and src/resources.config.ts. Do not edit: change the config and run `pnpm generate` again.
import type { TfProvider, TfResourceType } from "@sanoma/bridge/tfschema";
import { z } from "zod";

/** The OpenTofu provider these types are from. */
export const provider: TfProvider = {
  source: "integrations/github",
  version: "6.13.0",
  protocol: 5,
  sha256: "2d688e8383ff669297bbb6461f7eb05168f53fe76d3233fdb431e318efedb98f",
};

export const github_branch_protection = {
  typeName: "github_branch_protection",
  schemaVersion: 2,
  schema: z.object({
    allows_deletions: z.boolean().nullish().describe("Setting this to 'true' to allow the branch to be deleted."),
    allows_force_pushes: z.boolean().nullish().describe("Setting this to 'true' to allow force pushes on the branch."),
    enforce_admins: z
      .boolean()
      .nullish()
      .describe("Setting this to 'true' enforces status checks for repository administrators."),
    force_push_bypassers: z
      .array(z.string())
      .nullish()
      .describe(
        "The list of actor Names/IDs that are allowed to bypass force push restrictions. Actor names must either begin with a '/' for users or the organization name followed by a '/' for teams.",
      ),
    id: z.string().nullish(),
    lock_branch: z
      .boolean()
      .nullish()
      .describe("Setting this to 'true' will make the branch read-only and preventing any pushes to it."),
    pattern: z.string().describe("Identifies the protection rule pattern."),
    repository_id: z
      .string()
      .describe("The name or node ID of the repository associated with this branch protection rule."),
    require_conversation_resolution: z
      .boolean()
      .nullish()
      .describe(
        "Setting this to 'true' requires all conversations on code must be resolved before a pull request can be merged.",
      ),
    require_signed_commits: z
      .boolean()
      .nullish()
      .describe("Setting this to 'true' requires all commits to be signed with GPG."),
    required_linear_history: z
      .boolean()
      .nullish()
      .describe(
        "Setting this to 'true' enforces a linear commit Git history, which prevents anyone from pushing merge commits to a branch.",
      ),
    required_pull_request_reviews: z
      .array(
        z.object({
          dismiss_stale_reviews: z
            .boolean()
            .nullish()
            .describe("Dismiss approved reviews automatically when a new commit is pushed."),
          dismissal_restrictions: z
            .array(z.string())
            .nullish()
            .describe(
              "The list of actor Names/IDs with dismissal access. If not empty, 'restrict_dismissals' is ignored. Actor names must either begin with a '/' for users or the organization name followed by a '/' for teams.",
            ),
          pull_request_bypassers: z
            .array(z.string())
            .nullish()
            .describe(
              "The list of actor Names/IDs that are allowed to bypass pull request requirements. Actor names must either begin with a '/' for users or the organization name followed by a '/' for teams.",
            ),
          require_code_owner_reviews: z
            .boolean()
            .nullish()
            .describe("Require an approved review in pull requests including files with a designated code owner."),
          require_last_push_approval: z
            .boolean()
            .nullish()
            .describe("Require that The most recent push must be approved by someone other than the last pusher."),
          required_approving_review_count: z
            .number()
            .nullish()
            .describe(
              "Require 'x' number of approvals to satisfy branch protection requirements. If this is specified it must be a number between 0-6.",
            ),
          restrict_dismissals: z.boolean().nullish().describe("Restrict pull request review dismissals."),
        }),
      )
      .nullish()
      .describe("Enforce restrictions for pull request reviews."),
    required_status_checks: z
      .array(
        z.object({
          contexts: z
            .array(z.string())
            .nullish()
            .describe(
              "The list of status checks to require in order to merge into this branch. No status checks are required by default.",
            ),
          strict: z.boolean().nullish().describe("Require branches to be up to date before merging."),
        }),
      )
      .nullish()
      .describe("Enforce restrictions for required status checks."),
    restrict_pushes: z
      .array(
        z.object({
          blocks_creations: z.boolean().nullish().describe("Restrict pushes that create matching branches."),
          push_allowances: z
            .array(z.string())
            .nullish()
            .describe(
              "The list of actor Names/IDs that may push to the branch. Actor names must either begin with a '/' for users or the organization name followed by a '/' for teams.",
            ),
        }),
      )
      .nullish()
      .describe("Restrict who can push to matching branches."),
  }),
  fields: {
    immutable: ["repository_id"],
    vendorOwned: [],
    writeOnly: [],
  },
  shape: {
    attributes: [
      "allows_deletions",
      "allows_force_pushes",
      "enforce_admins",
      "force_push_bypassers",
      "id",
      "lock_branch",
      "pattern",
      "repository_id",
      "require_conversation_resolution",
      "require_signed_commits",
      "required_linear_history",
    ],
    blocks: {
      required_pull_request_reviews: {
        nesting: "list",
        shape: {
          attributes: [
            "dismiss_stale_reviews",
            "dismissal_restrictions",
            "pull_request_bypassers",
            "require_code_owner_reviews",
            "require_last_push_approval",
            "required_approving_review_count",
            "restrict_dismissals",
          ],
        },
      },
      required_status_checks: {
        nesting: "list",
        shape: {
          attributes: ["contexts", "strict"],
        },
      },
      restrict_pushes: {
        nesting: "list",
        shape: {
          attributes: ["blocks_creations", "push_allowances"],
        },
      },
    },
  },
} satisfies TfResourceType;

export const github_repository = {
  typeName: "github_repository",
  schemaVersion: 1,
  schema: z.object({
    allow_auto_merge: z
      .boolean()
      .nullish()
      .describe("Set to 'true' to allow auto-merging pull requests on the repository."),
    allow_forking: z
      .boolean()
      .nullish()
      .describe(
        "Set to 'true' to allow private forking on the repository; this is only relevant if the repository is owned by an organization and is private or internal.",
      ),
    allow_merge_commit: z.boolean().nullish().describe("Set to 'false' to disable merge commits on the repository."),
    allow_rebase_merge: z.boolean().nullish().describe("Set to 'false' to disable rebase merges on the repository."),
    allow_squash_merge: z.boolean().nullish().describe("Set to 'false' to disable squash merges on the repository."),
    allow_update_branch: z
      .boolean()
      .nullish()
      .describe("Set to 'true' to always suggest updating pull request branches."),
    archive_on_destroy: z
      .boolean()
      .nullish()
      .describe("Set to 'true' to archive the repository instead of deleting on destroy."),
    archived: z
      .boolean()
      .nullish()
      .describe(
        "Specifies if the repository should be archived. Defaults to 'false'. NOTE Currently, the API does not support unarchiving.",
      ),
    auto_init: z.boolean().nullish().describe("Set to 'true' to produce an initial commit in the repository."),
    default_branch: z
      .string()
      .nullish()
      .describe("Can only be set after initial repository creation, and only if the target branch exists")
      .meta({ deprecated: true }),
    delete_branch_on_merge: z
      .boolean()
      .nullish()
      .describe("Automatically delete head branch after a pull request is merged. Defaults to 'false'."),
    description: z.string().nullish().describe("A description of the repository."),
    etag: z.string().nullish(),
    fork: z.string().nullish().describe("Set to 'true' to fork an existing repository."),
    full_name: z.string().nullish().describe("A string of the form 'orgname/reponame'."),
    git_clone_url: z
      .string()
      .nullish()
      .describe("URL that can be provided to 'git clone' to clone the repository anonymously via the git protocol."),
    gitignore_template: z
      .string()
      .nullish()
      .describe("Use the name of the template without the extension. For example, 'Haskell'."),
    has_discussions: z
      .boolean()
      .nullish()
      .describe("Set to 'true' to enable GitHub Discussions on the repository. Defaults to 'false'."),
    has_downloads: z
      .boolean()
      .nullish()
      .describe("Set to 'true' to enable the (deprecated) downloads features on the repository.")
      .meta({ deprecated: true }),
    has_issues: z.boolean().nullish().describe("Set to 'true' to enable the GitHub Issues features on the repository"),
    has_projects: z
      .boolean()
      .nullish()
      .describe(
        "Set to 'true' to enable the GitHub Projects features on the repository. Per the GitHub documentation when in an organization that has disabled repository projects it will default to 'false' and will otherwise default to 'true'. If you specify 'true' when it has been disabled it will return an error.",
      ),
    has_wiki: z.boolean().nullish().describe("Set to 'true' to enable the GitHub Wiki features on the repository."),
    homepage_url: z.string().nullish().describe("URL of a page describing the project."),
    html_url: z.string().nullish().describe("URL to the repository on the web."),
    http_clone_url: z
      .string()
      .nullish()
      .describe("URL that can be provided to 'git clone' to clone the repository via HTTPS."),
    id: z.string().nullish(),
    ignore_vulnerability_alerts_during_read: z.boolean().nullish().meta({ deprecated: true }),
    is_template: z.boolean().nullish().describe("Set to 'true' to tell GitHub that this is a template repository."),
    license_template: z
      .string()
      .nullish()
      .describe("Use the name of the template without the extension. For example, 'mit' or 'mpl-2.0'."),
    merge_commit_message: z
      .string()
      .nullish()
      .describe("Can be 'PR_BODY', 'PR_TITLE', or 'BLANK' for a default merge commit message."),
    merge_commit_title: z
      .string()
      .nullish()
      .describe("Can be 'PR_TITLE' or 'MERGE_MESSAGE' for a default merge commit title."),
    name: z.string().describe("The name of the repository."),
    node_id: z.string().nullish().describe("GraphQL global node id for use with v4 API."),
    primary_language: z.string().nullish(),
    private: z.boolean().nullish().meta({ deprecated: true }),
    repo_id: z.number().nullish().describe("GitHub ID for the repository."),
    source_owner: z.string().nullish().describe("The owner of the source repository to fork from."),
    source_repo: z.string().nullish().describe("The name of the source repository to fork from."),
    squash_merge_commit_message: z
      .string()
      .nullish()
      .describe("Can be 'PR_BODY', 'COMMIT_MESSAGES', or 'BLANK' for a default squash merge commit message."),
    squash_merge_commit_title: z
      .string()
      .nullish()
      .describe("Can be 'PR_TITLE' or 'COMMIT_OR_PR_TITLE' for a default squash merge commit title."),
    ssh_clone_url: z
      .string()
      .nullish()
      .describe("URL that can be provided to 'git clone' to clone the repository via SSH."),
    svn_url: z
      .string()
      .nullish()
      .describe(
        "URL that can be provided to 'svn checkout' to check out the repository via GitHub's Subversion protocol emulation.",
      ),
    topics: z.array(z.string()).nullish().describe("The list of topics of the repository."),
    visibility: z
      .string()
      .nullish()
      .describe(
        "Can be 'public' or 'private'. If your organization is associated with an enterprise account using GitHub Enterprise Cloud or GitHub Enterprise Server 2.20+, visibility can also be 'internal'.",
      ),
    vulnerability_alerts: z
      .boolean()
      .nullish()
      .describe(
        "Set to 'true' to enable security alerts for vulnerable dependencies. Enabling requires alerts to be enabled on the owner level. (Note for importing: GitHub enables the alerts on all repos by default). Note that vulnerability alerts have not been successfully tested on any GitHub Enterprise instance and may be unavailable in those settings.",
      )
      .meta({ deprecated: true }),
    web_commit_signoff_required: z
      .boolean()
      .nullish()
      .describe("Require contributors to sign off on web-based commits."),
    pages: z
      .object({
        build_type: z.string().nullish().describe("The type the page should be sourced."),
        cname: z
          .string()
          .nullish()
          .describe(
            "The custom domain for the repository. This can only be set after the repository has been created.",
          ),
        custom_404: z.boolean().nullish().describe("Whether the rendered GitHub Pages site has a custom 404 page"),
        html_url: z.string().nullish().describe("URL to the repository on the web."),
        status: z.string().nullish().describe("The GitHub Pages site's build status e.g. building or built."),
        url: z.string().nullish(),
        source: z
          .object({
            branch: z
              .string()
              .describe("The repository branch used to publish the site's source files. (i.e. 'main' or 'gh-pages')"),
            path: z
              .string()
              .nullish()
              .describe("The repository directory from which the site publishes (Default: '/')"),
          })
          .nullish()
          .describe("The source branch and directory for the rendered Pages site."),
      })
      .nullish()
      .describe("The repository's GitHub Pages configuration")
      .meta({ deprecated: true }),
    security_and_analysis: z
      .object({
        advanced_security: z
          .object({
            status: z
              .string()
              .describe(
                "Set to 'enabled' to enable advanced security features on the repository. Can be 'enabled' or 'disabled', This value being present when split licensing is enabled will error out.",
              ),
          })
          .nullish()
          .describe(
            "The advanced security configuration for the repository. If a repository's visibility is 'public', advanced security is always enabled and cannot be changed, so this setting cannot be supplied.",
          ),
        code_security: z
          .object({
            status: z
              .string()
              .describe(
                "Set to 'enabled' to enable code security on the repository. Can be 'enabled' or 'disabled'. If set to 'enabled', the repository's visibility must be 'public', 'security_and_analysis[0].advanced_security[0].status' must also be set to 'enabled', or your Organization must have split licensing for Advanced security.",
              ),
          })
          .nullish()
          .describe("The code security configuration for the repository."),
        secret_scanning: z
          .object({
            status: z
              .string()
              .describe(
                "Set to 'enabled' to enable secret scanning on the repository. Can be 'enabled' or 'disabled'. If set to 'enabled', the repository's visibility must be 'public', 'security_and_analysis[0].advanced_security[0].status' must also be set to 'enabled', or your Organization must have split licensing for Advanced security.",
              ),
          })
          .nullish()
          .describe("The secret scanning configuration for the repository."),
        secret_scanning_ai_detection: z
          .object({
            status: z
              .string()
              .describe(
                "Set to 'enabled' to enable secret scanning AI detection on the repository. Can be 'enabled' or 'disabled'. If set to 'enabled', the repository's visibility must be 'public', 'security_and_analysis[0].advanced_security[0].status' must also be set to 'enabled', or your Organization must have split licensing for Advanced security.",
              ),
          })
          .nullish()
          .describe("The secret scanning AI detection configuration for this repository."),
        secret_scanning_non_provider_patterns: z
          .object({
            status: z
              .string()
              .describe(
                "Set to 'enabled' to enable secret scanning non-provider patterns on the repository. Can be 'enabled' or 'disabled'. If set to 'enabled', the repository's visibility must be 'public', 'security_and_analysis[0].advanced_security[0].status' must also be set to 'enabled', or your Organization must have split licensing for Advanced security.",
              ),
          })
          .nullish()
          .describe("The secret scanning non-provider patterns configuration for this repository."),
        secret_scanning_push_protection: z
          .object({
            status: z
              .string()
              .describe(
                "Set to 'enabled' to enable secret scanning push protection on the repository. Can be 'enabled' or 'disabled'. If set to 'enabled', the repository's visibility must be 'public', 'security_and_analysis[0].advanced_security[0].status' must also be set to 'enabled', or your Organization must have split licensing for Advanced security.",
              ),
          })
          .nullish()
          .describe("The secret scanning push protection configuration for the repository."),
      })
      .nullish()
      .describe(
        "Security and analysis settings for the repository. To use this parameter you must have admin permissions for the repository or be an owner or security manager for the organization that owns the repository.",
      ),
    template: z
      .object({
        include_all_branches: z
          .boolean()
          .nullish()
          .describe(
            "Whether the new repository should include all the branches from the template repository (defaults to 'false', which includes only the default branch from the template).",
          ),
        owner: z.string().describe("The GitHub organization or user the template repository is owned by."),
        repository: z.string().describe("The name of the template repository."),
      })
      .nullish()
      .describe("Use a template repository to create this resource."),
  }),
  fields: {
    immutable: [],
    vendorOwned: [
      "full_name",
      "git_clone_url",
      "html_url",
      "http_clone_url",
      "node_id",
      "primary_language",
      "repo_id",
      "ssh_clone_url",
      "svn_url",
      "pages.custom_404",
      "pages.html_url",
      "pages.status",
      "pages.url",
    ],
    writeOnly: [],
  },
  shape: {
    attributes: [
      "allow_auto_merge",
      "allow_forking",
      "allow_merge_commit",
      "allow_rebase_merge",
      "allow_squash_merge",
      "allow_update_branch",
      "archive_on_destroy",
      "archived",
      "auto_init",
      "default_branch",
      "delete_branch_on_merge",
      "description",
      "etag",
      "fork",
      "full_name",
      "git_clone_url",
      "gitignore_template",
      "has_discussions",
      "has_downloads",
      "has_issues",
      "has_projects",
      "has_wiki",
      "homepage_url",
      "html_url",
      "http_clone_url",
      "id",
      "ignore_vulnerability_alerts_during_read",
      "is_template",
      "license_template",
      "merge_commit_message",
      "merge_commit_title",
      "name",
      "node_id",
      "primary_language",
      "private",
      "repo_id",
      "source_owner",
      "source_repo",
      "squash_merge_commit_message",
      "squash_merge_commit_title",
      "ssh_clone_url",
      "svn_url",
      "topics",
      "visibility",
      "vulnerability_alerts",
      "web_commit_signoff_required",
    ],
    blocks: {
      pages: {
        nesting: "list",
        one: true,
        shape: {
          attributes: ["build_type", "cname", "custom_404", "html_url", "status", "url"],
          blocks: {
            source: {
              nesting: "list",
              one: true,
              shape: {
                attributes: ["branch", "path"],
              },
            },
          },
        },
      },
      security_and_analysis: {
        nesting: "list",
        one: true,
        shape: {
          attributes: [],
          blocks: {
            advanced_security: {
              nesting: "list",
              one: true,
              shape: {
                attributes: ["status"],
              },
            },
            code_security: {
              nesting: "list",
              one: true,
              shape: {
                attributes: ["status"],
              },
            },
            secret_scanning: {
              nesting: "list",
              one: true,
              shape: {
                attributes: ["status"],
              },
            },
            secret_scanning_ai_detection: {
              nesting: "list",
              one: true,
              shape: {
                attributes: ["status"],
              },
            },
            secret_scanning_non_provider_patterns: {
              nesting: "list",
              one: true,
              shape: {
                attributes: ["status"],
              },
            },
            secret_scanning_push_protection: {
              nesting: "list",
              one: true,
              shape: {
                attributes: ["status"],
              },
            },
          },
        },
      },
      template: {
        nesting: "list",
        one: true,
        shape: {
          attributes: ["include_all_branches", "owner", "repository"],
        },
      },
    },
  },
} satisfies TfResourceType;

export const github_team_membership = {
  typeName: "github_team_membership",
  schemaVersion: 0,
  schema: z.object({
    etag: z.string().nullish(),
    id: z.string().nullish(),
    role: z
      .string()
      .nullish()
      .describe("The role of the user within the team. Must be one of 'member' or 'maintainer'."),
    team_id: z.string().describe("The GitHub team id or the GitHub team slug."),
    username: z.string().describe("The user to add to the team."),
  }),
  fields: {
    immutable: ["team_id", "username"],
    vendorOwned: ["etag"],
    writeOnly: [],
  },
  shape: {
    attributes: ["etag", "id", "role", "team_id", "username"],
  },
} satisfies TfResourceType;
