import type { ResourceFields } from "@sanoma/workflows";
import type { ProviderRef } from "../bridge.ts";
import { blockOf } from "../json.ts";
import type { Attribute, Block, NestedBlock, NestedType, SchemaDocument } from "../schema.ts";
import { ctyToZod, key } from "./ctyToZod.ts";
import type { ResourcesConfig, TfBlockShape, TfProvider, TfShape } from "./types.ts";

/** Where `resources.gen.ts` came from, for its header and its `provider`. */
export interface GenerateSources {
  /** The pinned release the schema document is of, with its sha256. */
  provider: ProviderRef;
  /** The config's path, relative to the connector. */
  config: string;
}

/**
 * The source of a connector's `resources.gen.ts`: for each type `config.types` names, its zod
 * schema in the resource's shape, its flagged fields and its state layout. Pure: the same
 * document and config give the same text, so a regenerated file on a clean tree is no change.
 */
export function generateResources(doc: SchemaDocument, config: ResourcesConfig, sources: GenerateSources): string {
  const { source, version, sha256 } = sources.provider;
  if (doc.source !== source || doc.version !== version) {
    throw new Error(`the schema document is of ${doc.source} ${doc.version}, not the pinned ${source} ${version}`);
  }
  const unknown = config.types.filter((t) => !Object.hasOwn(doc.resources, t));
  if (unknown.length) throw new Error(`${doc.source} ${doc.version} has no resource type ${unknown.join(", ")}`);
  for (const [type, paths] of Object.entries(config.immutable ?? {})) {
    if (!config.types.includes(type)) throw new Error(`immutable names ${type}, which \`types\` does not list`);
    const block = doc.resources[type]!.block;
    const missing = paths.filter((path) => !hasPath(block, path));
    if (missing.length) throw new Error(`immutable: ${type} has no attribute ${missing.join(", ")}`);
  }

  const provider: TfProvider = { source, version, protocol: doc.protocol, ...(sha256 !== undefined && { sha256 }) };
  const out = [
    `// Generated by \`pnpm generate\` (@sanoma/bridge/tfschema) from the ${source} ${version} schema`,
    `// and ${sources.config}. Do not edit: change the config and run \`pnpm generate\` again.`,
    `import type { TfProvider, TfResourceType } from "@sanoma/bridge/tfschema";`,
    `import { z } from "zod";`,
    ``,
    `/** The OpenTofu provider these types are from. */`,
    `export const provider: TfProvider = ${literal(provider, "")};`,
  ];
  for (const type of config.types.toSorted()) {
    const { schemaVersion, block } = doc.resources[type]!;
    const fields = fieldsOf(block, config.immutable?.[type] ?? []);
    out.push(
      ``,
      ...docComment(block.description, ""),
      `export const ${type} = {`,
      `  typeName: ${JSON.stringify(type)},`,
      `  schemaVersion: ${schemaVersion},`,
      `  schema: ${blockSchema(block, "  ")},`,
      `  fields: ${literal(fields, "  ")},`,
      `  shape: ${literal(shapeOf(block), "  ")},`,
      `} satisfies TfResourceType;`,
    );
  }
  return `${out.join("\n")}\n`;
}

/** True when the block has the attribute or nested block at a dotted path (`required_status_checks.strict`). */
function hasPath(block: Block, path: string): boolean {
  const [name = "", ...rest] = path.split(".");
  if (rest.length === 0) return Object.hasOwn(block.attributes, name) || Object.hasOwn(block.blocks, name);
  const nestedType = block.attributes[name]?.nestedType;
  const nested = block.blocks[name]?.block ?? (nestedType && blockOf(nestedType));
  return nested !== undefined && hasPath(nested, rest.join("."));
}

/** `z.object({ … })` for a block: its attributes, then its nested blocks. */
function blockSchema(block: Block, indent: string): string {
  const inner = `${indent}  `;
  const lines = [
    ...Object.entries(block.attributes).map(([name, a]) => `${inner}${key(name)}: ${attributeSchema(a, inner)},`),
    ...Object.entries(block.blocks).map(([name, b]) => `${inner}${key(name)}: ${nestedBlockSchema(b, inner)},`),
  ];
  return lines.length ? `z.object({\n${lines.join("\n")}\n${indent}})` : "z.object({})";
}

function attributeSchema(a: Attribute, indent: string): string {
  const base = a.nestedType ? nestedTypeSchema(a.nestedType, indent) : ctyToZod(a.type);
  return annotate(a.required ? base : `${base}.nullish()`, a.description, a.deprecated);
}

/** A nested attribute (protocol 6), with each child's own flags: required children stay required. */
function nestedTypeSchema(nested: NestedType, indent: string): string {
  const object = blockSchema(blockOf(nested), indent);
  switch (nested.nesting) {
    case "single":
      return object;
    case "list":
    case "set":
      return `z.array(${object})`;
    case "map":
      return `z.record(z.string(), ${object})`;
  }
}

/**
 * A nested block: an object for `single` and `group`, and for a list or set of at most one
 * (SDKv2's way of saying "one object"); an array for other lists and sets; a record for `map`.
 * It may be left out unless the provider requires at least one.
 */
function nestedBlockSchema(b: NestedBlock, indent: string): string {
  const object = blockSchema(b.block, indent);
  const required = (b.minItems ?? 0) > 0;
  let base: string;
  if (b.nesting === "map") base = `z.record(z.string(), ${object})`;
  else if (b.nesting === "single" || b.nesting === "group" || isOne(b)) base = object;
  else base = `z.array(${object})${required ? `.min(${b.minItems})` : ""}`;
  return annotate(required ? base : `${base}.nullish()`, b.block.description, b.block.deprecated);
}

const isOne = (b: NestedBlock) => (b.nesting === "list" || b.nesting === "set") && b.maxItems === 1;

/** The description, as `.describe()`, and `deprecated` in the schema's metadata, which keeps the description. */
function annotate(zod: string, description: string | undefined, deprecated: boolean | undefined): string {
  const text = description?.trim();
  const described = text ? `${zod}.describe(${JSON.stringify(text)})` : zod;
  return deprecated ? `${described}.meta({ deprecated: true })` : described;
}

/** True when the attribute, or anything nested in it, is sensitive or write-only. */
const isSecret = (a: Attribute): boolean =>
  Boolean(a.sensitive || a.writeOnly || Object.values(a.nestedType?.attributes ?? {}).some(isSecret));

/** The flagged fields of a block, by dotted path: `vendorOwned`, `writeOnly`, `immutable` and `unordered` (sets). */
function fieldsOf(block: Block, immutable: string[]): ResourceFields {
  const vendorOwned: string[] = [];
  const writeOnly: string[] = [];
  const unordered: string[] = [];
  const walk = ({ attributes, blocks }: Block, prefix: string) => {
    for (const [name, a] of Object.entries(attributes)) {
      const path = prefix + name;
      if (a.computed && !a.optional && !a.required) vendorOwned.push(path);
      if ((Array.isArray(a.type) && a.type[0] === "set") || a.nestedType?.nesting === "set") unordered.push(path);
      if (isSecret(a)) writeOnly.push(path);
      else if (a.nestedType) walk(blockOf(a.nestedType), `${path}.`);
    }
    for (const [name, b] of Object.entries(blocks)) {
      if (b.nesting === "set" && !isOne(b)) unordered.push(prefix + name);
      walk(b.block, `${prefix + name}.`);
    }
  };
  walk(block, "");
  return { immutable: immutable.toSorted(), vendorOwned, writeOnly, unordered };
}

/** The state layout of a block, for `fromTfState` and `toTfState`. */
function shapeOf(block: Block): TfShape {
  const attributes = Object.keys(block.attributes);
  const secret = attributes.filter((name) => isSecret(block.attributes[name]!));
  const blocks = Object.entries(block.blocks).map(([name, b]): [string, TfBlockShape] => [
    name,
    { nesting: b.nesting, ...(isOne(b) && { one: true }), shape: shapeOf(b.block) },
  ]);
  return {
    attributes,
    ...(secret.length > 0 && { secret }),
    ...(blocks.length > 0 && { blocks: Object.fromEntries(blocks) }),
  };
}

/** A value as TypeScript source, indented to sit at `indent`. */
const literal = (value: unknown, indent: string) => JSON.stringify(value, null, 2).replaceAll("\n", `\n${indent}`);

/** A JSDoc comment of the description's first paragraph, or nothing. */
function docComment(description: string | undefined, indent: string): string[] {
  const text = description
    ?.trim()
    .split(/\n\s*\n/)[0]
    ?.replaceAll("*/", "*\\/");
  if (!text) return [];
  return [`${indent}/**`, ...text.split("\n").map((line) => `${indent} * ${line.trim()}`.trimEnd()), `${indent} */`];
}
